In [1]:
from EMAN2 import *
import tensorflow as tf
import numpy as np
from collections import Counter

2024-01-28 22:06:53.140184: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
tst=np.array([[1,2,3],[2,2,4],[3,2,1],[4,4,4],[5,1,2]])

In [13]:
tst2=np.array(sorted(tst,key=lambda x:x[2]))

In [14]:
tst2

array([[3, 2, 1],
       [5, 1, 2],
       [1, 2, 3],
       [2, 2, 4],
       [4, 4, 4]])

In [15]:
tst2[:,tst2[2]==4]

array([], shape=(5, 0), dtype=int64)

In [22]:
c=Counter(tst2[:,2])

In [23]:
c

Counter({1: 1, 2: 1, 3: 1, 4: 2})

In [24]:
nc=[c[i] for i in sorted(c)]

In [25]:
nc

[1, 1, 1, 2]

In [55]:
sz=[5,5,3]
ins=[tf.keras.layers.Input(w) for w in sz]
mid1=[tf.keras.layers.Dense(6)(i) for i in ins]
mid2=[tf.keras.layers.Dense(4)(i) for i in mid1]
out=tf.keras.layers.concatenate(mid2)
model=tf.keras.models.Model(inputs=ins,outputs=[out])

model

In [52]:
model.inputs[2].shape[1]

3

In [39]:
model.input_spec

[InputSpec(shape=(None, 8), ndim=2),
 InputSpec(shape=(None, 8), ndim=2),
 InputSpec(shape=(None, 8), ndim=2)]

model([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])

In [58]:
r=tf.RaggedTensor.from_row_lengths([1]*13,sz)

In [59]:
r

<tf.RaggedTensor [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1]]>

In [60]:
list(r)

[<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 1, 1, 1, 1], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 1, 1, 1, 1], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 1], dtype=int32)>]

In [66]:
in0=tf.keras.layers.Input(sum(sz))
ina=tf.keras.layers.Dense(5)(in0[0:5])
inb=tf.keras.layers.Dense(5)(in0[5:10])
inc=tf.keras.layers.Dense(5)(in0[10:13])
out2=tf.keras.layers.concatenate([ina,inb,inc])
model2=tf.keras.models.Model(inputs=in0,outputs=[out2])

In [68]:
model2.output

<KerasTensor: shape=(None, 15) dtype=float32 (created by layer 'concatenate_6')>